### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by tacgnol3**
I fixed some typo, only cosmetic.

### CODE REVIEW

**Review by DavidM42 — APPROVED** [review]
looks good to me 👍
Thank you for your contribution

**Comment by DavidM42** [comment]
Just one question before I'll merge it.
@tacgnol3 Just purely out of interest, do you actively use this script on any of your devices?

(I would have marked it as hacktoberfest-accepted but I think the PR was too late for that)

**Review by NiklasMerz — APPROVED** [review]
Change looks good.


@DavidM42 You may need to create a new installer with a new major version since this is breaking change. You could also consider crrating tags for versions and a changelog.

**Comment by tacgnol3** [comment]
@DavidM42 I used it for the first time last night, I found it randomly by searching how to set the governor to performance.

I use it on both my rpi4 and it work great so far. Then I saw the 'treshold' typo in the readme, and things went from there ...

I don't know if there is any implication with the install script with these changes tho.

Hope this help !

**Comment by DavidM42** [comment]
Ah okay, I really didn't expect anyone to stumble onto this project years after I forgot about it.
I'm glad it's working for you and is helping someone.

I'll merge it now and check if I can build a new version

**Pull request merged**
